// testimonialsData.js

const testimonials = [
  {
    id: 1,
    name: "Dr. Ananya Rao",
    position: "Senior Cardiologist",
    institution: "Apollo Hospitals",
    comment: "This platform has significantly improved our workflow.",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: 2,
    name: "Dr. Raghav Mehta",
    position: "Orthopedic Surgeon",
    institution: "Fortis Healthcare",
    comment: "User-friendly interface and excellent performance.",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: 3,
    name: "Dr. Sneha Iyer",
    position: "Medical Researcher",
    institution: "AIIMS Delhi",
    comment: "A reliable platform for both clinical and research use.",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: 4,
    name: "Dr. Vikram Singh",
    position: "Ophthalmologist",
    institution: "LV Prasad Eye Institute",
    comment: "Perfectly designed for ophthalmology professionals.",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: 5,
    name: "Dr. Kavya Nair",
    position: "Pediatric Specialist",
    institution: "Aster Hospitals",
    comment: "Helps streamline patient data access efficiently.",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    id: 6,
    name: "Dr. Arjun Malhotra",
    position: "Neurologist",
    institution: "Max Healthcare",
    comment: "Smooth performance and highly dependable system.",
    image: "https://randomuser.me/api/portraits/men/61.jpg",
  },
  {
    id: 7,
    name: "Dr. Pooja Kulkarni",
    position: "ENT Specialist",
    institution: "Manipal Hospitals",
    comment: "Clean UI and very intuitive design.",
    image: "https://randomuser.me/api/portraits/women/51.jpg",
  },
  {
    id: 8,
    name: "Dr. Sanjay Verma",
    position: "General Physician",
    institution: "Narayana Health",
    comment: "Makes daily clinical work much easier.",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 9,
    name: "Dr. Meera Joshi",
    position: "Gynecologist",
    institution: "Cloudnine Hospitals",
    comment: "Highly efficient and well-structured platform.",
    image: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    id: 10,
    name: "Dr. Amit Khanna",
    position: "Radiologist",
    institution: "SRL Diagnostics",
    comment: "Fast, accurate, and extremely helpful.",
    image: "https://randomuser.me/api/portraits/men/27.jpg",
  },
  {
    id: 11,
    name: "Dr. Neha Kapoor",
    position: "Dermatologist",
    institution: "Kaya Skin Clinic",
    comment: "Improved patient interaction and record handling.",
    image: "https://randomuser.me/api/portraits/women/73.jpg",
  },
  {
    id: 12,
    name: "Dr. Rahul Bansal",
    position: "Urologist",
    institution: "Medanta Hospital",
    comment: "Secure and very reliable system.",
    image: "https://randomuser.me/api/portraits/men/54.jpg",
  },
  {
    id: 13,
    name: "Dr. Shalini Gupta",
    position: "Pathologist",
    institution: "Dr. Lal PathLabs",
    comment: "Excellent for managing diagnostic workflows.",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 14,
    name: "Dr. Karthik Reddy",
    position: "Oncologist",
    institution: "Yashoda Hospitals",
    comment: "A must-have platform for modern hospitals.",
    image: "https://randomuser.me/api/portraits/men/66.jpg",
  },
  {
    id: 15,
    name: "Dr. Ayesha Khan",
    position: "Pulmonologist",
    institution: "Care Hospitals",
    comment: "Reliable, fast, and clinically accurate.",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
  },
  {
    id: 16,
    name: "Dr. Nitin Joshi",
    position: "Anesthesiologist",
    institution: "Ruby Hall Clinic",
    comment: "Well thought-out and easy to adopt.",
    image: "https://randomuser.me/api/portraits/men/41.jpg",
  },
  {
    id: 17,
    name: "Dr. Swati Deshpande",
    position: "Clinical Psychologist",
    institution: "MindCare Center",
    comment: "Helps maintain structured patient documentation.",
    image: "https://randomuser.me/api/portraits/women/56.jpg",
  },
  {
    id: 18,
    name: "Dr. Pradeep Iyer",
    position: "Gastroenterologist",
    institution: "Global Hospitals",
    comment: "Significantly boosts operational efficiency.",
    image: "https://randomuser.me/api/portraits/men/77.jpg",
  },
  {
    id: 19,
    name: "Dr. Ritu Malhotra",
    position: "Endocrinologist",
    institution: "Apollo Sugar Clinics",
    comment: "Simple, powerful, and very effective.",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    id: 20,
    name: "Dr. Manoj Patel",
    position: "Nephrologist",
    institution: "Sterling Hospitals",
    comment: "Consistent performance and excellent UI.",
    image: "https://randomuser.me/api/portraits/men/83.jpg",
  },
  {
    id: 21,
    name: "Dr. Divya Menon",
    position: "Ophthalmic Consultant",
    institution: "Sankara Eye Hospital",
    comment: "Especially useful for eye care professionals.",
    image: "https://randomuser.me/api/portraits/women/90.jpg",
  },
  {
    id: 22,
    name: "Dr. Harish Kumar",
    position: "Hospital Administrator",
    institution: "MIOT International",
    comment: "Improves coordination across departments.",
    image: "https://randomuser.me/api/portraits/men/91.jpg",
  },
];

export default testimonials;
